name: Dummy Deploy

on:
  push:
    branches:
      - main

jobs:
  dummy_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if it's past 5 PM
        id: check_time
        run: |
          current_hour=$(TZ=Asia/Kolkata date +"%H")
          echo $current_hour
          if [ "$current_hour" -ge 17 ]; then
            echo "stop_deployment=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "stop_deployment=false" >> $GITHUB_OUTPUT
          fi
      - name: My Deployment
        if: steps.check_time.outputs.stop_deployment != 'true'
        run : echo "Hello"